/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ui;

import Business.DTO.ProducDetailDTO;
import Business.DTO.ProductDTO;
import Business.Sevice.ProducSeviceDTO;
import DAL.Entity.Category;
import DAL.Entity.Color;
import DAL.Entity.Product;
import DAL.Entity.Product_1;
import DAL.Entity.ProductDetail;
import DAL.Entity.Size;
import DAL.Entity.Staff;
import DAL.Service.StaffService;
import Ui.ThungRac.ProductBin;
import Utils.BoxDiaglog;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import java.util.Scanner;
import java.util.UUID;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileSystemView;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Minh
 */
public class QuanLySanPham extends javax.swing.JFrame {

    /**
     * Creates new form QuanLySanPham
     */
    ProducSeviceDTO service;
    List<ProductDTO> listDTO;
    List<Category> listCategory;
    List<ProducDetailDTO> listDetailDTO;
    List<Size> listSize;
    List<Color> listColor;
    String idProduct;
    String kqAnh;
    
    int index;
    int indexDetail;
    public static String taiKhoan, maNV, tenNV, passNV;
    Staff staffLogin;
    StaffService staffService;
    
    
    public QuanLySanPham(String taiKhoan, String maNV, String tenNV, String passNV) {
        staffService = new StaffService();
        
        staffLogin = staffService.select_by_id(Login.userLogIn.getMaNhanVien());
        
        index = -1;
        indexDetail = -1;
        initComponents();
        service = new ProducSeviceDTO();
        listDTO = service.getAll();
        listCategory = service.loadCategery();
        listSize = service.loadSize();
        listColor = service.loadColor();
        this.taiKhoan = taiKhoan;
        this.maNV = maNV;
        this.tenNV = tenNV;
        this.passNV = passNV;
        loadCbo(listCategory);
        loadTable(listDTO);
        loadColor(listColor);
        LoadSize(listSize);

    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        textId = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        cboCategory = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableSP = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbDetailProduct = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        idDetail = new javax.swing.JTextField();
        giaDetail = new javax.swing.JTextField();
        giaBanDetail = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        soLuongDetail = new javax.swing.JTextField();
        cbbMau = new javax.swing.JComboBox<>();
        cbbSize = new javax.swing.JComboBox<>();
        lblTenSP = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        btnXoa = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        btnLammoi = new javax.swing.JButton();
        btnColo = new javax.swing.JButton();
        btnSize = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        btnNEw = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnThungrac = new javax.swing.JButton();
        btnEditCategory = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        lbHinh = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 145, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 461, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(74, 31, 61));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        textId.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Id");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Loại");

        tableSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên", "Loại", "Ảnh"
            }
        ));
        tableSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableSPMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableSP);

        jPanel4.setBackground(new java.awt.Color(186, 79, 84));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tbDetailProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Màu", "Size", "Số lượng", "Giá nhập", "Giá bán"
            }
        ));
        tbDetailProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDetailProductMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbDetailProduct);

        jPanel3.setBackground(new java.awt.Color(255, 255, 102));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Id");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Màu");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Size");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Giá nhập");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Giá bán");

        idDetail.setEnabled(false);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Số lượng");

        cbbMau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbMauActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel12)
                                .addComponent(jLabel9)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addGap(51, 51, 51)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idDetail)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(cbbMau, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(cbbSize, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(soLuongDetail, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(giaBanDetail, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(giaDetail))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(idDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbbMau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(cbbSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(giaDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(giaBanDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(soLuongDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(25, 25, 25))
        );

        lblTenSP.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTenSP.setText("Tên sản phẩm");

        jPanel7.setBackground(new java.awt.Color(255, 255, 102));

        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnLuu.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save1.png"))); // NOI18N
        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnLammoi.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnLammoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/newfile.png"))); // NOI18N
        btnLammoi.setText("Làm mới");
        btnLammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLammoiActionPerformed(evt);
            }
        });

        btnColo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnColo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/color-palette.png"))); // NOI18N
        btnColo.setText("Thêm màu");
        btnColo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColoActionPerformed(evt);
            }
        });

        btnSize.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/size.png"))); // NOI18N
        btnSize.setText("Thêm size");
        btnSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSizeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnLuu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLammoi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnColo)
                    .addComponent(btnSize))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLammoi, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnColo, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLuu)
                    .addComponent(btnSize))
                .addGap(34, 34, 34)
                .addComponent(btnXoa)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTenSP)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTenSP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 102));

        btnNEw.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnNEw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/newfile16.png"))); // NOI18N
        btnNEw.setText("Mới");
        btnNEw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNEwActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save16.png"))); // NOI18N
        btnSave.setText("Lưu");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/del16.png"))); // NOI18N
        btnDel.setText("Xóa");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(btnDel, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNEw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNEw)
                .addGap(18, 18, 18)
                .addComponent(btnSave)
                .addGap(18, 18, 18)
                .addComponent(btnDel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 255));
        jLabel10.setText("QUẢN LÝ SẢN PHẨM");

        btnThungrac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bin.png"))); // NOI18N
        btnThungrac.setText("Thùng rác");
        btnThungrac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThungracActionPerformed(evt);
            }
        });

        btnEditCategory.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnEditCategory.setText("Chỉnh sủa thể loại");
        btnEditCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditCategoryActionPerformed(evt);
            }
        });

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Tìm kiếm theo tên");

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        jButton11.setText("Tìm kiếm");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbHinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbHinhMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbHinh, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbHinh, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 364, Short.MAX_VALUE)
                        .addComponent(btnThungrac)
                        .addGap(5, 12, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(61, 61, 61)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cboCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(textId, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel4)
                                            .addComponent(btnEditCategory)
                                            .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addComponent(jLabel13)
                                                .addGap(51, 51, 51)
                                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(35, 35, 35)
                                                .addComponent(jButton11)))))
                                .addGap(18, 18, 18)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5)
                                        .addGap(13, 13, 13)
                                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(textId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2))
                                        .addGap(26, 26, 26)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3))
                                        .addGap(29, 29, 29)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(cboCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4))
                                        .addGap(2, 2, 2)))
                                .addGap(18, 18, 18)
                                .addComponent(btnEditCategory))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(btnThungrac)
                                .addGap(26, 26, 26))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton11))
                                .addGap(45, 45, 45)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 27, Short.MAX_VALUE))
        );

        jButton12.setText("Thoát");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton12)
                        .addGap(9, 9, 9)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:\
        if (index < 0) {
            BoxDiaglog.alert(this, "Chọn sản phẩm");
            return;
        }
        UUID uuid = UUID.randomUUID();

        String id = uuid.toString();
        int idSize = listSize.get(cbbSize.getSelectedIndex()).getMaSize();
        int idColor = listColor.get(cbbMau.getSelectedIndex()).getMaMau();
        int soLuong;
        int giaBan;
        int giaNhap;

        try {
            giaBan = Integer.parseInt(giaBanDetail.getText());
        } catch (NumberFormatException e) {
            BoxDiaglog.alert(this, "Giá bán nhập không đúng định dạng số");
            return;
        }

        try {
            soLuong = Integer.parseInt(soLuongDetail.getText());
        } catch (NumberFormatException e) {
            BoxDiaglog.alert(this, "Số lượng nhập không đúng định dạng số");
            return;
        }

        try {
            giaNhap = Integer.parseInt(giaDetail.getText());
        } catch (NumberFormatException e) {
            BoxDiaglog.alert(this, "Giá nhập không đúng định dạng số");
            return;
        }

        ProductDetail pd = new ProductDetail(id, "bo di nhe", soLuong, giaNhap, giaBan, idProduct, null, idSize, idColor, true);
        //public ProductDetail(String maSanPhamChiTiet, String tenSanPham, int soLuong, int giaNhap, int giaBan, String maSanPham, String maTheLoai, int maSize, int maMau, boolean trangThai) {

        String nameSize = listSize.get(cbbSize.getSelectedIndex()).getTenSize();
        String nameColor = listColor.get(cbbMau.getSelectedIndex()).getTenMau();
        for (ProducDetailDTO x : listDetailDTO) {
            if (x.getSize().equals(nameSize) && x.getMau().equals(nameColor)) {
                BoxDiaglog.alert(this, "Màu và size đã tồn tài trong sản phẩm");
                return;
            }
        }

        if (indexDetail >= 0) {
            String idUpdate = idDetail.getText();
            pd.setMaSanPhamChiTiet(idUpdate);
            listDetailDTO.set(indexDetail, new ProducDetailDTO(idUpdate, nameColor, nameSize, soLuong, giaNhap, giaBan));
            loadTableDetailProduct(listDetailDTO);
            service.updateProductDetail(pd);
        } else {
            listDetailDTO.add(new ProducDetailDTO(id, nameColor, nameSize, soLuong, giaNhap, giaBan));
            loadTableDetailProduct(listDetailDTO);
            service.inSertProductDetail(pd);
        }

    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnLammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLammoiActionPerformed
        // TODO add your handling code here:

        idDetail.setText("");
        giaBanDetail.setText("");
        giaDetail.setText("");
        soLuongDetail.setText("");
        cbbMau.setSelectedIndex(0);
        cbbSize.setSelectedIndex(0);
        indexDetail = -1;
    }//GEN-LAST:event_btnLammoiActionPerformed

    private void cbbMauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbMauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbMauActionPerformed

    private void tbDetailProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDetailProductMouseClicked
        // TODO add your handling code here:
        indexDetail = tbDetailProduct.getSelectedRow();

        dispay2(indexDetail);

    }//GEN-LAST:event_tbDetailProductMouseClicked

    private void tableSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableSPMouseClicked
        // TODO add your handling code here:

        index = tableSP.getSelectedRow();
        if (index >= 0) {
            ProductDTO p = listDTO.get(index);
            listDetailDTO = service.getProductDetai(p.getId());
            loadTableDetailProduct(listDetailDTO);
            lblTenSP.setText(p.getTenSanPham());
            idProduct = p.getId();
            updateHinh(p.getAnh());

            dispay(index);
        }
    }//GEN-LAST:event_tableSPMouseClicked

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        // TODO add your handling code here:
        String id = listDTO.get(index).getId();

        service.deleteSoft(id);
        listDTO.remove(index);
        loadTable(listDTO);
        DefaultTableModel model = (DefaultTableModel) tbDetailProduct.getModel();
        model.setRowCount(0);
        idDetail.setText("");
        giaBanDetail.setText("");
        giaDetail.setText("");
        soLuongDetail.setText("");
        index = -1;
        textId.setText("");
        txtName.setText("");
        cboCategory.setSelectedIndex(0);


    }//GEN-LAST:event_btnDelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        UUID uuid = UUID.randomUUID();

        Product newProduct = new Product();
        String id = uuid.toString();
        String name = txtName.getText();
        String anh = kqAnh;
        String idCategory = listCategory.get(cboCategory.getSelectedIndex()).getMaTheLoai();
        String nameCategory = listCategory.get(cboCategory.getSelectedIndex()).getTenTheLoai();
        if (name.equals("")) {
            BoxDiaglog.alert(this, "Tên không được để trống");
            return;
        }

        newProduct.setTrangThai(1);
        newProduct.setMaSanPham(id);
        newProduct.setTenSanPham(name);
        newProduct.setMaTheLoai(idCategory);
        newProduct.setAnh(anh);

        if (index < 0) {

            service.createProduct(newProduct);
            listDTO.add(new ProductDTO(id, name, nameCategory, anh));
            BoxDiaglog.alert(this, "Thêm mới thành công");
        } else {
            String idOLD = listDTO.get(index).getId();
            newProduct.setMaSanPham(idOLD);

            service.UpdateProduct(newProduct);

            listDTO.set(index, new ProductDTO(textId.getText(), name, nameCategory, anh));
            BoxDiaglog.alert(this, "Sửa thành công");
        }

        loadTable(listDTO);

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnNEwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNEwActionPerformed
        // TODO add your handling code here:
        index = -1;
        textId.setText("");
        txtName.setText("");
        cboCategory.setSelectedIndex(0);
    }//GEN-LAST:event_btnNEwActionPerformed

    private void lbHinhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbHinhMouseClicked
        // TODO add your handling code here:
        chonAnh();


    }//GEN-LAST:event_lbHinhMouseClicked

    public void chonAnh() {
        kqAnh = null;
        try {
            JFileChooser fc = new JFileChooser();
            int hoi = fc.showDialog(this, "Chọn ảnh");
            if (hoi == JFileChooser.APPROVE_OPTION) {
            }
            kqAnh = fc.getSelectedFile().getName();
            updateHinh(kqAnh);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi chọn ảnh!!", "Chú ý:", JOptionPane.INFORMATION_MESSAGE, icon);
        }
    }

    public void updateHinh(String image) {
        try {
            ImageIcon icon1 = new ImageIcon("C:\\Users\\tiennv\\Desktop\\ShopAdam\\src\\img\\AnhSanPham\\" + image);
            Image im = icon1.getImage();
            ImageIcon icon = new ImageIcon(im.getScaledInstance(lbHinh.getWidth(), lbHinh.getHeight(), im.SCALE_SMOOTH));
            lbHinh.setIcon(icon);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi đường dẫn ảnh!!", "Chú ý:", JOptionPane.INFORMATION_MESSAGE, icon);
        }
    }
    private void btnThungracActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThungracActionPerformed
        // TODO add your handling code here:
        
        ProductBin thungRac = new ProductBin();
        thungRac.pack();
        thungRac.setVisible(true);

    }//GEN-LAST:event_btnThungracActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        if (indexDetail < 0) {
            BoxDiaglog.alert(this, "Chọn sản phẩm cần xóa");
        } else {
            String idProduct = listDetailDTO.get(indexDetail).getMaSPCT();
            service.deleteSoftProductDetail(idProduct);
            listDetailDTO.remove(indexDetail);
            BoxDiaglog.alert(this, "Xóa sản phẩm thành công!");
            loadTableDetailProduct(listDetailDTO);
        }
        indexDetail = -1;
        idDetail.setText("");
        giaBanDetail.setText("");
        giaDetail.setText("");
        soLuongDetail.setText("");
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnEditCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditCategoryActionPerformed
        // TODO add your handling code here:
        this.dispose();
        QLLoaiSP qllsp = new QLLoaiSP(taiKhoan, maNV, tenNV, passNV);
        qllsp.setVisible(true);
    }//GEN-LAST:event_btnEditCategoryActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        String textSearch = txtSearch.getText();
        List<Product> listProuduct = service.finbyName(textSearch);
        listDTO.clear();
        for (Product x : listProuduct) {
            ProductDTO dto = new ProductDTO();
            dto.setId(x.getMaSanPham());
            dto.setTenSanPham(x.getTenSanPham());
            dto.setLoaiSanPham(x.getMaTheLoai());
             dto.setAnh(x.getAnh());
            listDTO.add(dto);

        }
        loadTable(listDTO);


    }//GEN-LAST:event_jButton11ActionPerformed

    private void btnColoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColoActionPerformed
        // TODO add your handling code here:
       
        QuanLyMau qlm = new QuanLyMau();
        qlm.setVisible(true);
    }//GEN-LAST:event_btnColoActionPerformed

    private void btnSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSizeActionPerformed
        // TODO add your handling code here:
        QuanLySize qls = new QuanLySize();
        qls.setVisible(true);
    }//GEN-LAST:event_btnSizeActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Home home = new Home(staffLogin.getTaiKhoan(), staffLogin.getMaNhanVien(), staffLogin.getTenNhanVien(), staffLogin.getMatKhau());
        home.setVisible(true);
    }//GEN-LAST:event_jButton12ActionPerformed
    ImageIcon icon;

    public void dispay2(int index2) {
        if (indexDetail >= 0) {
            idDetail.setText(listDetailDTO.get(index2).getMaSPCT());
            giaDetail.setText(String.valueOf(listDetailDTO.get(index2).getGiaNhap()));
            giaBanDetail.setText(String.valueOf(listDetailDTO.get(index2).getGiaBan()));
            soLuongDetail.setText(String.valueOf(listDetailDTO.get(index2).getSoLuong()));
            cbbMau.setSelectedItem(listDetailDTO.get(index2).getMau());
            cbbSize.setSelectedItem(listDetailDTO.get(index2).getSize());

        }
    }

//    public void dispay(int index) {
//        textId.setText(listDTO.get(index).getId());
//        txtName.setText(listDTO.get(index).getTenSanPham());
//         cboCategory.setSelectedItem(listDTO.get(index).getLoaiSanPham());
//        
//    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLySanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLySanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLySanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLySanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLySanPham(taiKhoan, maNV, tenNV, passNV).setVisible(true);
            }
        });
    }

    public void loadTable(List<ProductDTO> list) {
        DefaultTableModel model = (DefaultTableModel) tableSP.getModel();
        model.setRowCount(0);
        for (ProductDTO x : list) {
            model.addRow(new Object[]{x.getTenSanPham(), x.getLoaiSanPham(), x.getAnh()});

        }

    }

    public void loadCbo(List<Category> list) {
        for (Category x : list) {
            cboCategory.addItem(x.getTenTheLoai());
        }
    }

    public void loadColor(List<Color> list) {

        for (Color x : list) {
            cbbMau.addItem(x.getTenMau());
        }
    }

    public void LoadSize(List<Size> list) {
        for (Size x : list) {
            cbbSize.addItem(x.getTenSize());
        }
    }

    public void dispay(int index) {
        String anh = listDTO.get(index).getAnh();
        ImageIcon icon = new ImageIcon("C:\\Users\\Minh\\Desktop\\DA2\\DuAn1-QLBH-Nhom1\\src\\img" + anh);
        //  lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/photo_2021-11-20_07-37-52.jpg"))); // NOI18N
        textId.setText(listDTO.get(index).getId());
        txtName.setText(listDTO.get(index).getTenSanPham());
        cboCategory.setSelectedItem(listDTO.get(index).getLoaiSanPham());

    }
    //ImageIO newImage = yourImage.getScaledInstance(newWidth, newHeight, Image.SCALE_DEFAULT);

    public void loadTableDetailProduct(List<ProducDetailDTO> list) {
        DefaultTableModel model = (DefaultTableModel) tbDetailProduct.getModel();
        model.setRowCount(0);
        for (ProducDetailDTO x : list) {
            model.addRow(new Object[]{
                x.getMau(),
                x.getSize(),
                x.getSoLuong(),
                x.getGiaNhap(),
                x.getGiaBan(),});

        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnColo;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnEditCategory;
    private javax.swing.JButton btnLammoi;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnNEw;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSize;
    private javax.swing.JButton btnThungrac;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbbMau;
    private javax.swing.JComboBox<String> cbbSize;
    private javax.swing.JComboBox<String> cboCategory;
    private javax.swing.JTextField giaBanDetail;
    private javax.swing.JTextField giaDetail;
    private javax.swing.JTextField idDetail;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbHinh;
    private javax.swing.JLabel lblTenSP;
    private javax.swing.JTextField soLuongDetail;
    private javax.swing.JTable tableSP;
    private javax.swing.JTable tbDetailProduct;
    private javax.swing.JTextField textId;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
